

services:

  #  PostgreSQL 
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  #  Auth Service (port 3001) 
  auth-service:
    build:
      context: .
      args:
        SERVICE_NAME: auth-service
    environment:
      AUTH_DATABASE_URL: postgres://postgres:password@postgres:5432/auth_db
      JWT_SECRET: super-tajni-kljuc-za-development
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

  #  User Service (port 3002) 
  user-service:
    build:
      context: .
      args:
        SERVICE_NAME: user-service
    environment:
      USER_DATABASE_URL: postgres://postgres:password@postgres:5432/user_db
      JWT_SECRET: super-tajni-kljuc-za-development
    ports:
      - "3002:3002"
    depends_on:
      postgres:
        condition: service_healthy

  #  Event Service (port 3003) 
  event-service:
    build:
      context: .
      args:
        SERVICE_NAME: event-service
    environment:
      EVENT_DATABASE_URL: postgres://postgres:password@postgres:5432/event_db
      JWT_SECRET: super-tajni-kljuc-za-development
    ports:
      - "3003:3003"
    depends_on:
      postgres:
        condition: service_healthy

  #  Registration Service (port 3004)
  registration-service:
    build:
      context: .
      args:
        SERVICE_NAME: registration-service
    environment:
      REGISTRATION_DATABASE_URL: postgres://postgres:password@postgres:5432/registration_db
      EVENT_SERVICE_URL: http://event-service:3003
      JWT_SECRET: super-tajni-kljuc-za-development
    ports:
      - "3004:3004"
    depends_on:
      postgres:
        condition: service_healthy
      event-service:
        condition: service_started

  #  API Gateway (port 3000) 
  api-gateway:
    build:
      context: .
      args:
        SERVICE_NAME: api-gateway
    environment:
      AUTH_SERVICE_URL: http://auth-service:3001
      USER_SERVICE_URL: http://user-service:3002
      EVENT_SERVICE_URL: http://event-service:3003
      REGISTRATION_SERVICE_URL: http://registration-service:3004
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
      - event-service
      - registration-service

volumes:
  postgres_data:
